name: Deploy updates

on:  
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Check for source changes
        id: check
        run: echo "deploy=$(bun run ./ci/action_check_update.ts ${{ secrets.SERVER_DEPLOY_KEY }})" >> "$GITHUB_OUTPUT"

      - name: Trigger server update
        if: contains(steps.check.outputs.deploy, 'server')
        run: curl -X GET https://wowexport.net/services/internal/update?key=${{ secrets.SERVER_DEPLOY_KEY }}

      - name: Setup node.js
        if: contains(steps.check.outputs.deploy, 'patch')
        uses: actions/setup-node@v3
        with:
            node-version: 20

      - name: Install global dependencies
        if: contains(steps.check.outputs.deploy, 'patch')
        run: npm install --global nwjs-installer resedit-cli

      - name: bun install
        if: contains(steps.check.outputs.deploy, 'patch')
        run: bun install

      - name: Compile wow.export win-x64
        if: contains(steps.check.outputs.deploy, 'patch')
        run: bun run build-release

      - name: Upload build to patch server
        if: contains(steps.check.outputs.deploy, 'patch')
        run: bun ./ci/action_update_patch.ts ${{ secrets.SERVER_DEPLOY_KEY }}

        # TODO: Re-add GitHub release creation