name: Deploy wow.export

on:  
  push:
    tags:
      - '*'
jobs: 
  build:
    if: ${{ !startsWith(github.event.ref, 'refs/tags/pre-') }}
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup vlang
        uses: vlang/setup-v@v1.3
        with:
            version: '0.3.4'

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install GNU C compiler for MinGW-w64
        run: sudo apt-get install gcc-mingw-w64-x86-64

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install global dependencies
        run: npm install --global nwjs-installer resedit-cli

      - name: bun install
        run: bun install

      - name: Compile wow.export win-x64
        run: bun run build-release

      - name: Publish
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
          SFTP_REMOTE_UPDATE_DIR: ${{ secrets.SFTP_REMOTE_UPDATE_DIR }}
          SFTP_REMOTE_PACKAGE_DIR: ${{ secrets.SFTP_REMOTE_UPDATE_DIR }}
        run: bun run publish

      - name: Upload release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: bin\packages\wow.export-*.zip
