name: server_deploy

on:  
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for relevant source changes
        run: | 
          local_head=$(git rev-parse HEAD)
          remote_head=$(curl -s https://wowexport.net/services/internal/head?key=${{ secrets.SERVER_DEPLOY_KEY }})

          if git diff --name-only $local_head $remote_head | grep -q -F -f ./workflow_triggers/server_deploy.txt; then
            echo "changes detected, triggering remote update"
            curl -X POST https://wowexport.net/services/internal/update?key=${{ secrets.SERVER_DEPLOY_KEY }}
          else
            echo "no changes detected"
          fi