name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install TypeScript (for ESLint)
        run: bun add --global typescript

      - name: ESlint check
        run: bun x eslint .

      - name: Run tests
        run: bun test